Update Path types for list to single value
Updated getParametersByPathSync and getParametersByPath path type to PSParameterName, Since these two methods throwing below error
```
 throw new Error( queryResult.err.message || queryResult.err.code );
                  ^
Error: Expected params.Path to be a string  
File: param_query.js:99:19
```